obj-y += ir_defs.o ir_match.o ir_opt.o
obj-y += main_main.o main_globals.o main_util.o
obj-y += host_x86_defs.o host_amd64_defs.o host_arm_defs.o host_ppc_defs.o
obj-y += host_x86_isel.o host_amd64_isel.o host_arm_isel.o host_ppc_isel.o
obj-y += host_generic_regs.o host_generic_simd64.o host_generic_simd128.o host_generic_reg_alloc2.o
obj-y += guest_generic_x87.o guest_generic_bb_to_IR.o
obj-y += guest_x86_helpers.o guest_amd64_helpers.o guest_arm_helpers.o guest_ppc_helpers.o
obj-y += guest_x86_toIR.o guest_amd64_toIR.o guest_arm_toIR.o guest_ppc_toIR.o
